---
- name: Configure rkhunter
  become: true
  ansible.builtin.template:
    src: "{{ rkhunter_template }}"
    dest: /etc/default/rkhunter
    backup: true
    mode: "0644"
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  notify:
    - Run rkhunter propupd
  tags:
    - packages
    - rkhunter
    - M1049

- name: SSH root access should be disabled
  become: true
  ansible.builtin.lineinfile:
    regexp: ALLOW_SSH_ROOT_USER
    line: ALLOW_SSH_ROOT_USER=no
    dest: /etc/rkhunter.conf
    mode: "0640"
    state: present
    create: false
    backrefs: true
  notify:
    - Run rkhunter propupd
  tags:
    - packages
    - rkhunter
    - M1049

- name: SSH v1 should not be used
  become: true
  ansible.builtin.lineinfile:
    regexp: (^#|^)ALLOW_SSH_PROT_V1
    line: ALLOW_SSH_PROT_V1=2
    dest: /etc/rkhunter.conf
    mode: "0640"
    state: present
    create: false
    backrefs: true
  notify:
    - Run rkhunter propupd
  tags:
    - packages
    - rkhunter
    - M1049

- name: Allow expected shm files in rkhunter
  become: true
  ansible.builtin.lineinfile:
    regexp: '^ALLOWDEVFILE={{ item.regex }}$'
    line: 'ALLOWDEVFILE={{ item.line }}'
    dest: /etc/rkhunter.conf
    mode: "0640"
    state: present
    create: false
    backrefs: false
  loop:
    - regex: '/dev/shm/zbx\.buffer'
      line: '/dev/shm/zbx.buffer'
    - regex: '/dev/shm/squid-cf__readers\.shm'
      line: '/dev/shm/squid-cf__readers.shm'
    - regex: '/dev/shm/squid-cf__queues\.shm'
      line: '/dev/shm/squid-cf__queues.shm'
    - regex: '/dev/shm/squid-cf__metadata\.shm'
      line: '/dev/shm/squid-cf__metadata.shm'
    - regex: '/dev/shm/PostgreSQL\.\*'
      line: '/dev/shm/PostgreSQL.*'
  notify:
    - Run rkhunter propupd
  tags:
    - packages
    - rkhunter
    - M1049
